version: "3.9"

services:
  server:
    build:
      target: prod_build
    command: npm run server-start

  nginx:
    image: nginx
    build:
      context: ./nginx-prod
    ports:
      - 0.0.0.0:80:80
    volumes:
      - .:/var/www/
    restart: unless-stopped
    networks:
      - polaview.network
    depends_on:
      - scraper
      - server

  scraper:
    image: scraper
    build:
      target: prod_build
    command: npm run scraper-start
