FROM node:lts as dev_build

RUN mkdir -p /api/

WORKDIR /api

COPY tsconfig.node.json /api/tsconfig.node.json
COPY tsconfig.json /api/tsconfig.json
COPY package.json /api/package.json

COPY shared /api/shared
COPY prisma /api/prisma
COPY .env /api/.env
COPY server /api/server

COPY node_modules /api/node_modules

# Prisma routine
RUN npx prisma generate

EXPOSE 8080

FROM dev_build as prod_build

RUN npm run server-build