version: "3.9"

services:
  auth-layer:
    image: auth-layer
    build:
      context: .
      dockerfile: Dockerfile.auth-layer
      target: dev_build
    networks:
      - polaview.network
    ports:
      - 8080:8080
    restart: unless-stopped
    tty: true
    command: npm run auth-layer-dev
    depends_on:
      - postgres
      - cache
    volumes:
      - ./auth-layer:/api/auth-layer
      - ./shared:/api/shared
      - ./node_modules:/api/node_modules

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      target: dev_build
    networks:
      - polaview.network
    ports:
      - 5173:5173
      - 3010:3010
    restart: unless-stopped
    tty: true
    command: npm run client-dev
    volumes:
      - ./src:/client/src
      - ./shared:/client/shared
      - ./node_modules:/client/node_modules

  nginx:
    image: nginx
    build:
      context: ./nginx
    ports:
      - 0.0.0.0:80:80
    volumes:
      - .:/var/www/
    restart: unless-stopped
    networks:
      - polaview.network
    depends_on:
      - data-layer
      - client
      - auth-layer

  data-layer:
    image: data-layer
    build:
      context: .
      dockerfile: Dockerfile.data-layer
      target: dev_build
    networks:
      - polaview.network
    depends_on:
      - cache
      - postgres
    ports:
      - 8081:8081
    restart: unless-stopped
    command: npm run data-layer-dev
    volumes:
      - ./data-layer:/data-layer/data-layer
      - ./shared:/data-layer/shared
      - ./node_modules:/data-layer/node_modules
      - /home/${USER}/Videos:/openMedia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - count: 1
    #           capabilities: [gpu]
    #           # driver: nvidia

  cache:
    image: redis
    container_name: cache
    expose:
      - 6379
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - polaview.network

  postgres:
    container_name: pg_container
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=polaview
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - polaview.network

networks:
  polaview.network:
    driver: bridge

volumes:
  db:
    driver: local
  redis_data:
    driver: local
