version: "3.9"

services:
  nginx:
    image: nginx
    build:
      context: ./nginx-prod
    ports:
      - 0.0.0.0:80:80
    volumes:
      - .:/var/www/
    restart: unless-stopped
    networks:
      - polaview.network
    depends_on:
      - data-layer
      - auth-layer
