version: "3.9"

services:
  nginx:
    image: nginx
    build:
      context: ./nginx-prod
    ports:
      - 0.0.0.0:80:80
      - 443:443
    volumes:
      - .:/var/www/
      - ./sslCertificates:/etc/nginx/certs
    restart: unless-stopped
    networks:
      - polaview.network
    depends_on:
      - data-layer
      - auth-layer
