version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      - polaview.network
    ports:
      - 8080:8080
    restart: unless-stopped
    tty: true
    command: npm run server-dev
    depends_on:
      - postgres
    volumes:
      - ./server:/api/server
      - ./shared:/api/shared
      - /media/${USER}:/openMedia
      - /home/${USER}:/openMedia
      - ./node_modules:/api/node_modules

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      - polaview.network
    ports:
      - 5173:5173
      - 3010:3010
    restart: unless-stopped
    tty: true
    command: npm run client-dev
    volumes:
      - ./src:/client/src
      - ./shared:/client/shared
      - ./node_modules:/client/node_modules

  nginx:
    image: nginx
    build:
      context: ./nginx
    ports:
      - 0.0.0.0:80:80
    volumes:
      - .:/var/www/
    restart: unless-stopped
    networks:
      - polaview.network
    depends_on:
      - scrapimdb
      - client
      - server

  scrapimdb:
    image: scrapimdb
    build:
      context: .
      dockerfile: Dockerfile.scrapimdb
    networks:
      - polaview.network
    ports:
      - 8081:8081
    restart: unless-stopped
    command: npm run scrapimdb-dev
    volumes:
      - ./scrapimdb:/scrapper/scrapimdb
      - ./shared:/scrapper/shared
      - ./node_modules:/client/node_modules

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=polaview
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - polaview.network

networks:
  polaview.network:
    driver: bridge

volumes:
  db:
    driver: local
